### ISSUE TITLE
代码逻辑疑问

### ISSUE THREAD

**Issue by xiedi-w** [fuhao0536/box-im-master#1]
**私聊消息对方不在线代码阅读疑问**

发送私聊消息，如果对方不在线的处理逻辑没看懂，监听器广播也没看到对应的处理
![image](https://github.com/fuhao0536/box-im-master/assets/53244726/48863286-f47b-4ba1-a032-be4ad3244ac9)
私聊监听器没看到对应的处理逻辑呢
![image](https://github.com/fuhao0536/box-im-master/assets/53244726/d1986959-41b2-4da4-9993-51ef1433b464)

**Comment by xiedi-w** [comment]
第一张图的，红框内的代码是否是多余的呢，大佬👀

**Comment by felizdevida** [comment]
当对方不在线时，发送成功，会有websocket长连接，实现浏览器发送文本回写，并且检测到浏览器上线，netty的同步处理，消息存到redis中，当用户上线时，有一个定时器推送消息，是实现上线接收消息，并且更新接收消息状态。相关问题，可以自己部署本地或者服务器，自己操作一下，追踪信息，熟悉下流程

**Comment by xiedi-w** [comment]
嗯，我看代码逻辑是，对方不在线，存储未读消息，netty 获取到登陆信息后，查询未读消息，放到redis。登陆后从redis中获取未读的消息。
但是我没看懂第一张图的，红框内的代码。
为什么要发送一个不在线的消息呢，而且我看监听器并没有对这个消息对象处理，那几个判断都没覆盖到，是我忽略了什么步骤了吗

**Comment by felizdevida** [comment]
目前是作为一个发送消息的状态码标记一下，是有一个提示信息的，目前还在完善中

**Comment by xiedi-w** [comment]
好的 🫡
