### ISSUE TITLE
server端集群部署问题

### ISSUE THREAD

**Issue by xiedi-w** [fuhao0536/box-im-master#2]
**服务器支持集群化部署，每个im-server仅处理自身连接用户的消息**

这个需要把前台和后台建立连接的ws连接改一下吧，要走一个代理。从多个server端选择一个建立连接吧
除此之外还需要做其他的么🧐

![image](https://github.com/fuhao0536/box-im-master/assets/53244726/0eb1a970-46b3-44bd-978f-08d269de6620)

**Comment by felizdevida** [comment]
本地部署后不用更改

**Comment by xiedi-w** [comment]
hello 如果要集群部署操作步骤是什么呢？🫶

**Comment by felizdevida** [comment]
您部署集群的目的是什么？

**Comment by xiedi-w** [comment]
就像您开源一样，抱着学习的态度想跑一下
